### ISSUE TITLE
Fast option and SCALrecommendation

### ISSUE THREAD

**Issue by olelod** [equinor/pyscal#226]
It would be nice if the fast option was available also when using the SCALrecommendation functionality

**Comment by berland** [comment]
How is this used? The `SCALrecommendation` constructor accepts ready-made `WaterOilGas` objects, and these should be initialized with the `fast` option.

**Comment by olelod** [comment]
I was only just thinking about this. 

Currently I use the` pyscalfactory.create_scal_recommendation_list,` providing a dataframe with CASE and SATNUM columns in addition to all the parameters needed to generate the `WaterOilGas` objects.

(https://github.com/equinor/flownet/blob/64edc2fcebc75e1172a465668b8594d6c5ed9300/src/flownet/parameters/_relative_permeability.py#L157)

**Comment by berland** [comment]
Got it! The factory module also needs to support fast mode.
