### ISSUE TITLE
Improve definitions for Sgro, Sgrw and Sgcr and introduce kro(Sgro)

### ISSUE THREAD

**Issue by richypitman** [equinor/pyscal#257]
Improvement suggestions from SCAL group:

- Add Sgro parameter (for gas condensate "gas-oil" models, currently handled by sgcr)
- Add kro(Sgro) parameter (for gas condensate "gas-oil" models, currently no endpoint relative permeability is defined at this point)
- Extend Sgrw to apply to both water and gas curves (for "gas-water" models, currently sgrw applies only to the water curve, while sgcr applies to both the gas and water curves)
- Redefine Sgcr so that it is used only as a critical saturation and not a residual saturation (e.g. in "gas-oil" models where Sg is increasing, not in cases where Sg is decreasing as for gas condensate fields)

**Comment by berland** [comment]
> * Add Sgro parameter (for gas condensate "gas-oil" models, currently handled by sgcr)
> * Add kro(Sgro) parameter (for gas condensate "gas-oil" models, currently no endpoint relative permeability is defined at this point)

These should be covered by #256 

> * Extend Sgrw to apply to both water and gas curves (for "gas-water" models, currently sgrw applies only to the water curve, while sgcr applies to both the gas and water curves)

I don't see how sgcr affects the water curve for the two-phase Gas-Water. In the corresponding figure it does not. Is there a bug? Is the suggestion to remove sgcr from GasWater and use sgrw in its place?

> * Redefine Sgcr so that it is used only as a critical saturation and not a residual saturation (e.g. in "gas-oil" models where Sg is increasing, not in cases where Sg is decreasing as for gas condensate fields)

How can this be accomplished? Pyscal has no notion of increasing or decreasing saturations.

**Comment by richypitman** [comment]
> > * Add Sgro parameter (for gas condensate "gas-oil" models, currently handled by sgcr)
> > * Add kro(Sgro) parameter (for gas condensate "gas-oil" models, currently no endpoint relative permeability is defined at this point)
> 
> These should be covered by #256
> 

- Very good 

> > * Extend Sgrw to apply to both water and gas curves (for "gas-water" models, currently sgrw applies only to the water curve, while sgcr applies to both the gas and water curves)
> 
> I don't see how sgcr affects the water curve for the two-phase Gas-Water. In the corresponding figure it does not. Is there a bug? Is the suggestion to remove sgcr from GasWater and use sgrw in its place?

- Replacing sgcr with Sgrw is an option. Sgrw is the **residual** gas saturation after water invasion and affects both krg and krw. A critical saturation at the end of a cycle makes no sense to me; that is where residual saturations are found. In this case, the residual is Sgrw but currently seems to be handled by a critical gas saturation 'sgcr'. I believe this is simply a nomenclature issue and perhaps reflects differing terms used by the SCAL/res eng/res modelling communities.

> 
> > * Redefine Sgcr so that it is used only as a critical saturation and not a residual saturation (e.g. in "gas-oil" models where Sg is increasing, not in cases where Sg is decreasing as for gas condensate fields)
> 
> How can this be accomplished? Pyscal has no notion of increasing or decreasing saturations.

- It is not for pyscal to know but the coders/users, with guidance from the documentation. Compare a "gas-oil" case where the model represents a gas-condensate field versus an oil field with gas cap expansion and/or injection. In the gas-condensate case, the input gas-oil kr model starts with high gas saturation (no critical gas saturation) and ends at the residual gas saturation, _Sgro_. In the oil field case, the input gas-oil kr model starts with zero gas saturation and ends at the residual oil saturation, _Sorg_. In this oil field case, it is reasonable to also consider a critical gas saturation, _Sgcr_, at the start of the cycle, i.e. the point at which gas bubbles coalesce and start to flow. This is a **critical** saturation. Residual and critical should not be interchangeable terms and this causes confusion when delivering SCAL models. We want to ensure we can deliver SCAL models in the correct format for pyscal and FMU workflows.

**Comment by berland** [comment]
> > > * Extend Sgrw to apply to both water and gas curves (for "gas-water" models, currently sgrw applies only to the water curve, while sgcr applies to both the gas and water curves)
> > I don't see how sgcr affects the water curve for the two-phase Gas-Water. In the corresponding figure it does not. Is there a bug? Is the suggestion to remove sgcr from GasWater and use sgrw in its place?
> * Replacing sgcr with Sgrw is an option. Sgrw is the **residual** gas saturation after water invasion and affects both krg and krw. A critical saturation at the end of a cycle makes no sense to me; that is where residual saturations are found. In this case, the residual is Sgrw but currently seems to be handled by a critical gas saturation 'sgcr'. I believe this is simply a nomenclature issue and perhaps reflects differing terms used by the SCAL/res eng/res modelling communities.

Issue #260 should solve this.

**Comment by berland** [comment]
> * It is not for pyscal to know but the coders/users, with guidance from the documentation. Compare a "gas-oil" case where the model represents a gas-condensate field versus an oil field with gas cap expansion and/or injection. In the gas-condensate case, the input gas-oil kr model starts with high gas saturation (no critical gas saturation) and ends at the residual gas saturation, _Sgro_. In the oil field case, the input gas-oil kr model starts with zero gas saturation and ends at the residual oil saturation, _Sorg_. In this oil field case, it is reasonable to also consider a critical gas saturation, _Sgcr_, at the start of the cycle, i.e. the point at which gas bubbles coalesce and start to flow. This is a **critical** saturation. Residual and critical should not be interchangeable terms and this causes confusion when delivering SCAL models. We want to ensure we can deliver SCAL models in the correct format for pyscal and FMU workflows.

Thanks. I guess this must be implemented outside pyscal, as pyscal can't distuingish between 3-phase oil-gas-water and 3 phase condensate-gas-water. 

But, Pyscal could "guess" that if SGRO is non-zero, it is gas-condensate, and then apply some extra checks on f.ex. SGCR, providing a warning (or error?) if SGCR is not equal to SGRO.

**Comment by berland** [comment]
Covered by the other aforementioned issues/prs.
