### ISSUE TITLE
Increase MAX_EXPONENT in constants.py

### ISSUE THREAD

**Issue by richypitman** [equinor/pyscal#352]
I'd like to suggest increasing MAX_EXPONENT in constants.py, which is currently set to 100. As noted in constants.py, it can be far higher than 100 but 100 is sufficient for relative permeability. It is, however, relevant to have a higher max exponent value for capillary pressure. I encountered this limitation when using the add_LET_pc_imb method of the WaterOil class. 

I suggest a MAX_EXPONENT value of 3000 to account for the far higher LET exponent values seen in capillary pressure parameterisation. Alternatively, there could be two separate max exponent variables, e.g. MAX_EXPONENT_KR for rel perm set at 100 and a MAX_EXPONENT_PC for capillary pressure set at 3000. 

From contants.py:
```
 * ``MAX_EXPONENT``: Maximal number for exponents in relperm parametrizations.
   Used to avoid numerical instabilities. It could probably be much
   higher than the chosen number in most circumstances, but such high
   numbers should not be relevant for relative permeability
   
   MAX_EXPONENT: float = 100
```

**Comment by richypitman** [comment]
I'd like to have a crack at fixing this, since I brought it up so long ago.

**Comment by alifbe** [comment]
Resolve in #406
