### ISSUE TITLE
WaterOilGas Model

### ISSUE THREAD

**Issue by Maryelin-31** [equinor/pyscal#368]
Hello, My name is Maryelin.

I want to use your library to build relative permeability data for use in my seepage simulation model built by my research group. However, when I try to get the result, there is an issue with the function wog.gasoil.add_corey_water()

it appears this attribute error:

'GasOil' object has no attribute 'add_corey_water'

**Comment by berland** [comment]
You probably mean `wog.wateroil.add_corey_water()`. It does not make sense to add water curves to the gasoil-part of a WaterOilGas object.

**Comment by Maryelin-31** [comment]
I thought that, and I did it, Thank you. But at the beginning, I just was following the examples in the documentation https://equinor.github.io/pyscal/usage.html
There may be a mistake there

**Comment by Maryelin-31** [comment]
Thank you so much. 

Sorry to bother you, but I'm new to python and I'm learning how to use libraries and other things. Can you tell me if there is a way to export the results to a CVS file, or somehow export the relative permeability results?

**Comment by berland** [comment]
Check this function https://equinor.github.io/pyscal/pyscal/pyscal.pyscallist.html#pyscal.pyscallist.PyscalList.df
