### ISSUE TITLE
Mismatch between versions on pypi and github?

### ISSUE THREAD

**Issue by Blunde1** [equinor/pyscal#380]
From github and pypi I see
![image](https://user-images.githubusercontent.com/13650516/186851054-f2ffa3d0-deb5-4337-afa1-c085917900ba.png)
![image](https://user-images.githubusercontent.com/13650516/186851078-bcf2370d-0538-4ec5-9a9a-88a4773fe8f5.png)
Are these versions (`v0.9.3` and `v0.10.0`) the same?

**Comment by berland** [comment]
Solved now, re-uploaded 0.10.0 and deleted 0.9.3 from pypi.
