### ISSUE TITLE
Fails with scipy==1.9.3

### ISSUE THREAD

**Issue by berland** [equinor/pyscal#384]
Pyscal is not compatible with scipy 1.9.3.

Most likely same problem as https://github.com/equinor/xtgeo/issues/811

**Comment by berland** [comment]
Solved (temporarily) by pinning.

**Comment by kwinkunks** [comment]
Issue fixed in `scipy` and resolved in `xtgeo`, checking `pyscal`.

**Comment by kwinkunks** [comment]
Upgraded `scipy` to 1.10.1 and `pyscal` fails on 37 tests with

    ValueError: Expect x to not have duplicates

See #388
