### ISSUE TITLE
Unpin scipy

### ISSUE THREAD

**Issue by berland** [equinor/pyscal#388]
scipy is pinned to 1.9.3 in #385 , see issue #384 . This restriction must be lifted, either in pyscal or in scipy.

**Comment by kwinkunks** [comment]
I believe the issue was resolved in SciPy -- a fix was merged in August 2022: https://github.com/scipy/scipy/pull/16780

However, I upgraded `scipy` to 1.10.1 and `pyscal` fails on 37 tests with

    ValueError: Expect x to not have duplicates

So I'll leave this alone for now.
