### ISSUE TITLE
Error when running example "from pyscal import WaterOilGas"

### ISSUE THREAD

**Issue by lixuekai2001** [equinor/pyscal#402]
In the document (https://equinor.github.io/pyscal/usage.html), there is an example for 3 phases flow "Water-oil-gas (https://equinor.github.io/pyscal/usage.html#water-oil-gas)"

The example code is:
```
from pyscal import WaterOilGas

wog = WaterOilGas(swl=0.05, sorg=0.04, sorw=0.03)
wog.wateroil.add_corey_water()
wog.wateroil.add_corey_oil()
wog.gasoil.add_corey_gas()
wog.gasoil.add_corey_water()
```
which result in an error:

```
AttributeError                            Traceback (most recent call last)
Cell In[5], line 7
      5 wog.wateroil.add_corey_oil()
      6 wog.gasoil.add_corey_gas()
----> 7 wog.gasoil.add_corey_water()

AttributeError: 'GasOil' object has no attribute 'add_corey_water'
```

The solution for the error is easy. It is because there is no "**add_corey_water**" in gasoil.py.
So one should change "**wog.gasoil.add_corey_water()**"  to be:

**wog.gasoil.add_corey_water()**

**Comment by alifbe** [comment]
Hi @lixuekai2001 
Thank you for reporting. We'll fix and update the documentation :+1:
