### ISSUE TITLE
Error in running GasWater

### ISSUE THREAD

**Issue by lixuekai2001** [equinor/pyscal#403]
The example code is:

```
from pyscal import GasWater
gw = GasWater(swl=0.05, sgrw=0.1, sgcr=0.2)
gw.add_corey_water()
gw.add_corey_gas()
print(gw.SWFN())
```
Error in the output is:

`ERROR:pyscal.wateroil:KRW data should be contained in [0,1]
`

**Comment by alifbe** [comment]
@lixuekai2001 Unfortunately, I cannot reproduce this error message. The snippet is working fine on my end. What is the pyscal version that you have?

**Comment by alifbe** [comment]
Close since it's not reproducible
