### ISSUE TITLE
Add docs link to main GitHub page

### ISSUE THREAD

**Issue by kwinkunks** [equinor/pyscal#422]
Needs an admin.

Could add the link to the public docs: https://equinor.github.io/pyscal/ -- I usually look for it on other libraries, at least.

**Comment by alifbe** [comment]
@kwinkunks  We have link to the docs in README.md  Or do you mean something else? :smile: 

https://github.com/equinor/pyscal/blob/c8c385b0250f6ba340b18fe96bc0d4a44cf8fea4/README.md?plain=1#L15-L17
