### ISSUE TITLE
Hypothesis test failure - test_slgof.py::test_slgof_hypo

### ISSUE THREAD

**Issue by mferrera** [equinor/pyscal#444]
A test case generate by hypothesis failed.

```sh
FAILED tests/test_slgof.py::test_slgof_hypo - AssertionError
Falsifying example: test_slgof_hypo(
    swl=0.0,
    sorg=0.15625,
    sgcr=0.15504997195913137,
    h=1e-07,
)

You can reproduce this example by temporarily adding @reproduce_failure('6.104.1',b'AXicY2BABgcUwBQTiKnvdC8/O3APkHmwUD/46pR/WwFrKwmp') as a decorator on your test case
```

**Comment by berland** [comment]
The problem is likely related to rounding of floating point numbers, which is always problematic in IEE754.

```
(Pdb) round(0.843749972, 5)
0.84375
(Pdb) round(0.843749972*10000, 5)
8437.49972
(Pdb) round(0.843749972*10000)
8437
```
which happens in
https://github.com/equinor/pyscal/blob/main/src/pyscal/gasoil.py#L157-L158
that code assumes that the first and last round statement above yielded the same values.

**Comment by berland** [comment]
The problem seems related to these floating point details:

```
>>> value_1 = 0.8437499719590555
>>> round(value_1 * 10000)  # this is what Pyscal uses to drop duplicates
8437
>>> print(f"{value_1:.5f}")  # This is how values are printed
0.84375
>>> value2 = 0.84375
>>> round(value2 * 10000)
8438  # different integer, so it will not be regarded as similar to value_1
>>> print(f"{value2:.5f}")
0.84375  # But formatted equivalent to value_1
```
This happens in  `GasOil.__init__()`

**Comment by berland** [comment]
Still flaky after #458 
```
FAILED tests/test_slgof.py::test_slgof_hypo - AssertionError
Falsifying example: test_slgof_hypo(
    swl=0.02432496616483698,
    sorg=1e-07,
    sgcr=0.02432496616483698,
    h=1e-07,
)

You can reproduce this example by temporarily adding @reproduce_failure('6.112.2', b'AXicY2BgOBDw9/fETYGFDAwMBwv1g69O+beVAasoAKBtE7s=') as a decorator on your test case
```

**Comment by alifbe** [comment]
I think the issue is with the latest PR. Since `SWINTEGERS` is multiplied by factor of 10. `h_min` is now even smaller and causing the issue (probably even more severe). I propose we do what you did and change this line `h_min = 10.0 / float(SWINTEGERS)`

https://github.com/equinor/pyscal/blob/d6f0bf7c3a272615ba12f57ed88d112f01b46626/src/pyscal/gasoil.py#L92

**Comment by berland** [comment]
Agree, `h_min` should have been adjusted in #458
