### ISSUE TITLE
pyscal performance

### ISSUE THREAD

**Issue by wouterjdb** [equinor/pyscal#56]
It takes about 0.07-0.10 seconds from initializing a WaterOilGas object to writing out both SWOF and SGOF. In most use cases this is completely fine. 👍 

However, in some special use cases, with many relative permeability curves being created, this time quickly adds up. (In my case I'm creating 1000 curves in 100 realization with 4 iterations = 11 hrs compute time).

It would be great to see if there are any (obvious) performance gains to be made.

**Comment by wouterjdb** [comment]
```
Initializing WaterOilGas   ~0.25 s
Adding 4x Corey            ~0.25 s
Printing SWOF+SGOF         ~0.25 s
```
It seems to be quite evenly distributed. I suspect that the performance is limited by the many Pandas operations that are performed. As this is heavily integrated in the code it is not easy to simply switch it out with numpy arrays.

**Comment by berland** [comment]
The `selfcheck()` and `crosspoint()` calls in `WaterOil.SWOF()` are natural candidates for shaving off in a performance critical mode.

**Comment by berland** [comment]
@wouterjdb , is there a need to keep this open any longer?

**Comment by wouterjdb** [comment]
I still have an open issue on implementing this functionality. I observed initialization errors in Flow when using the fast method. See: https://github.com/equinor/ddpd-flownet/pull/172

**Comment by wouterjdb** [comment]
Tested the fast option: that works now.

Another learning is that multiple pyscal curves can be much quicker generated by using `concurrent.futures`.

These two solutions mean that this issue can now be closed.
