### ISSUE TITLE
Capillary pressure entries set to zero

### ISSUE THREAD

**Issue by eivindsm** [equinor/pyscal#89]
The script subscript/interp_relperm use pyscal.scalrecommendation to interpolate between flow curves. Due to an issue in pyscal probably related to the add_fromtable function, Pc curves are set to zero as opposed to being set to whatever the table contain.

**Comment by berland** [comment]
Do you have a reproducible setup for the bug?

**Comment by eivindsm** [comment]
Yes, sorry should have added that immediately!
/project/fmu/users/eism/r003/r003_20200124/ert/input/relperm and interp_relerpm.yaml reproduces this

**Comment by eivindsm** [comment]
It seems this issue is already fixed. Master version does indeed treat read in Pc from the table as it should. Thanks for the great work, close the issue.
